# Generated by Django 4.2.11 on 2024-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion_oficio', models.CharField(max_length=40)),
                ('codigo_postal', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_del_auto', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
                ('codigo_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MalaPraxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=40)),
                ('codigo_postal', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('año', models.IntegerField()),
            ],
        ),
    ]
