# Generated by Django 4.2.11 on 2024-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hogar_delete_malapraxis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('documento', models.CharField(choices=[('Documento Nacional de Identidad', 'Documento Nacional de Identidad'), ('Libreta Civica', 'Libreta Civica'), ('Libreta de Enrolamiento', 'Libreta de Enrolamiento'), ('CUIT', 'CUIT')], max_length=40)),
                ('numero', models.IntegerField(verbose_name=20)),
                ('n_celular', models.IntegerField(verbose_name=15)),
                ('correo_electronico', models.CharField(max_length=40)),
            ],
        ),
    ]
