# Generated by Django 4.2.11 on 2024-03-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_art_codigo_postal_alter_art_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='tipo_propiedad',
            field=models.CharField(choices=[('Departamento_Dos_Ambientes', 'Departamento_Dos_Ambientes'), ('Casa', 'Casa'), ('PH', 'PH'), ('Departamento_Tres_Ambientes', 'Departamento_Tres_Ambientes'), ('Departamento_Cuatro_Ambientes', 'Departamento_Cuatro_Ambientes')], max_length=30),
        ),
    ]
