# Generated by Django 4.2.11 on 2024-03-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_hogar_tipo_propiedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vida',
            old_name='numero',
            new_name='n_numero',
        ),
        migrations.RenameField(
            model_name='vida',
            old_name='documento',
            new_name='tipo_documento',
        ),
    ]
