# Generated by Django 4.2.11 on 2024-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_numero_vida_n_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['profesion_oficio'], 'verbose_name': 'Art', 'verbose_name_plural': 'Art'},
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['marca_del_auto'], 'verbose_name': 'Auto', 'verbose_name_plural': 'Auto'},
        ),
        migrations.AlterModelOptions(
            name='hogar',
            options={'ordering': ['tipo_propiedad'], 'verbose_name': 'Hogar', 'verbose_name_plural': 'Hogar'},
        ),
        migrations.AlterModelOptions(
            name='vida',
            options={'ordering': ['nombre'], 'verbose_name': 'Vida', 'verbose_name_plural': 'Vida'},
        ),
        migrations.AddField(
            model_name='vida',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
