# Generated by Django 4.2.11 on 2024-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_art_precio_art_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=1000, max_digits=20)),
                ('muerte_accidental', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('invalidez_parcial_total_permanente', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('gastos_asistencia_medica', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoIndependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=510, max_digits=3)),
                ('muerte_accidental', models.DecimalField(decimal_places=2, default=1500000, max_digits=8)),
                ('invalidez_parcial_total_permanente', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('gastos_asistencia_medica', models.DecimalField(decimal_places=2, default=150000, max_digits=15)),
            ],
        ),
    ]
