# Generated by Django 4.2.11 on 2024-03-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profesionales_trabajoindependiente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesionales',
            new_name='Dependiente',
        ),
    ]
