# Generated by Django 4.2.11 on 2024-03-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_coberturaparcial_todoriesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Cuatro_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Dos_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Tres_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Un_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=101, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=2500, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=2000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
    ]
